# Add goto option to use a specified config file as database configuration
# After adding, all other options can be removed
# goto: 'path/to/database.yml'

# Database type, available options: sqlite and mysql
type: sqlite
# Table name prefix
table_prefix: 'sweettask_'
# JDBC parameters
query: 'useSSL=false&allowPublicKeyRetrieval=true&verifyServerCertificate=false&serverTimezone=UTC'
# Connection pool settings
hikari:
  max_lifetime: 120000
  idle_timeout: 10000
  connection_timeout: 5000
  minimum_idle: 8
  maximum_pool_size: 36
# MySQL settings
mysql:
  host: localhost
  port: 3306
  user: 'root'
  pass: 'root'
  database: minecraft
# SQLite settings
sqlite:
  file: 'database.db'
